# Generated by Django 4.2 on 2025-11-20 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EstiloObra', '0001_initial'),
        ('Propietario', '0001_initial'),
        ('Artistas', '0001_initial'),
        ('TipoObra', '0001_initial'),
        ('MedioObra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=150)),
                ('PrecioSugerido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FueVendida', models.BooleanField(default=False)),
                ('PrecioVenta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Activo', models.BigIntegerField(default=True)),
                ('IdArtista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Artistas.artista')),
                ('IdEstilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EstiloObra.estilosdeobra')),
                ('IdMedio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MedioObra.mediosdeobra')),
                ('IdPropietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Propietario.propietario')),
                ('IdTipoObra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TipoObra.tiposdeobra')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
    ]
