# Generated by Django 4.2 on 2026-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='Descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='Estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('exhibicion', 'En exhibición'), ('vendida', 'Vendida')], default='disponible', max_length=20),
        ),
    ]
