# Generated by Django 4.2 on 2025-11-20 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Vendedores', '0001_initial'),
        ('Obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=20)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('FechaCreacion', models.DateField(auto_now_add=True)),
                ('Activo', models.BigIntegerField(default=True)),
                ('IdCliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.clientes')),
                ('IdVendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Vendedores.vendedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Activo', models.BooleanField(default=True)),
                ('IdFactura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salidas.factura')),
                ('IdObra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Obras.obras')),
            ],
            options={
                'verbose_name': 'DetalleFactura',
                'verbose_name_plural': 'DetallesFacturas',
            },
        ),
    ]
