# Generated by Django 4.2 on 2025-11-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Lugar', models.CharField(max_length=50)),
                ('Tematica', models.CharField(blank=True, max_length=200, null=True)),
                ('FechaInicio', models.DateField()),
                ('FechaFinalizacion', models.DateField()),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exposición',
                'verbose_name_plural': 'Exposiciones',
            },
        ),
    ]
