# Generated by Django 4.2 on 2026-04-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Lugar', models.CharField(max_length=50)),
                ('Tematica', models.CharField(blank=True, max_length=200, null=True)),
                ('FechaInicio', models.DateField()),
                ('FechaFinalizacion', models.DateField()),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exposición',
                'verbose_name_plural': 'Exposiciones',
            },
        ),
        migrations.CreateModel(
            name='ObrasEnExposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendida', models.BooleanField(default=False)),
                ('FechaExposicion', models.DateField()),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Exposicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Exposicion.exposicion')),
                ('Obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Obras.obras')),
            ],
            options={
                'verbose_name': 'Obra en Exposición',
                'verbose_name_plural': 'Obras en Exposición',
                'unique_together': {('Obra', 'Exposicion')},
            },
        ),
    ]
