# Generated by Django 4.2 on 2025-11-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Cedula', models.CharField(max_length=39)),
                ('Telefono', models.CharField(max_length=20)),
                ('FechaNaciminiento', models.DateField()),
                ('Correo', models.CharField(max_length=100)),
                ('RFC', models.CharField(max_length=9)),
                ('Activo', models.BigIntegerField(default=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
    ]
