# Generated by Django 4.2 on 2026-04-08 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='Cedula',
            field=models.CharField(max_length=39, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='RFC',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
