# Generated by Django 4.2 on 2026-03-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
    ]
