# Generated by Django 4.2 on 2026-04-07 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exposicion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Tipo_Gasto', models.CharField(help_text='Ejemplo: Materiales, Servicios, etc.', max_length=100, verbose_name='Tipo de Gasto')),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha', models.DateField(verbose_name='Fecha del Gasto')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Exposicion', models.ForeignKey(blank=True, help_text='Seleccione la exposición relacionada con este gasto, si aplica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='Exposicion.exposicion', verbose_name='Exposición Relacionada')),
                ('Obras', models.ManyToManyField(blank=True, help_text='Seleccione las obras relacionadas con este gasto, si aplica.', related_name='gastos', to='Obras.obras', verbose_name='Obras Relacionadas')),
                ('Responsable', models.ForeignKey(blank=True, help_text='Seleccione el usuario responsable de este gasto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Gasto')),
            ],
            options={
                'verbose_name': 'Gasto Interno',
                'verbose_name_plural': 'Gastos Internos',
            },
        ),
    ]
