# Generated by Django 4.2 on 2026-03-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GastoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Tipo_Gasto', models.CharField(max_length=100)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha', models.DateField()),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Responsable', models.CharField(max_length=100)),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gasto Interno',
                'verbose_name_plural': 'Gastos Internos',
            },
        ),
    ]
