# Generated by Django 4.2 on 2026-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Cedula',
            field=models.CharField(max_length=39, unique=True),
        ),
    ]
