# Generated by Django 4.2 on 2025-11-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=5)),
                ('NombreTipo', models.CharField(max_length=100)),
                ('Activo', models.BigIntegerField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Obra',
                'verbose_name_plural': 'Tipos Obras',
            },
        ),
    ]
